// An additional, distinct word in each day's bilingual reading.
const readingExtras = [
    ['schedule', 'lịch trình', 'A simple schedule helps me start the morning calmly.', 'Một lịch trình đơn giản giúp tôi bắt đầu buổi sáng bình tĩnh.'],
    ['packed lunch', 'bữa trưa mang theo', 'I prepare a packed lunch before leaving home.', 'Tôi chuẩn bị bữa trưa mang theo trước khi rời nhà.'],
    ['lobby', 'sảnh', 'I meet a new colleague in the lobby.', 'Tôi gặp một đồng nghiệp mới ở sảnh.'],
    ['rapport', 'mối quan hệ hòa hợp', 'Good rapport makes teamwork more comfortable.', 'Mối quan hệ hòa hợp giúp làm việc nhóm thoải mái hơn.'],
    ['perseverance', 'sự bền bỉ', 'Perseverance helps me continue after a difficult day.', 'Sự bền bỉ giúp tôi tiếp tục sau một ngày khó khăn.'],
    ['bookmark', 'dấu trang', 'I save a useful page with a bookmark.', 'Tôi lưu một trang hữu ích bằng dấu trang.'],
    ['ritual', 'thói quen cố định', 'A short evening ritual helps me remember what I learned.', 'Một thói quen ngắn vào buổi tối giúp tôi nhớ điều đã học.'],

    ['craft', 'nghề thủ công', 'Learning a craft gives me a relaxing hobby.', 'Học một nghề thủ công cho tôi một sở thích thư giãn.'],
    ['detergent', 'chất giặt tẩy', 'I buy detergent before doing the laundry.', 'Tôi mua chất giặt tẩy trước khi giặt đồ.'],
    ['quorum', 'số người tối thiểu để họp', 'We wait for a quorum before starting the meeting.', 'Chúng tôi chờ đủ số người tối thiểu trước khi bắt đầu họp.'],
    ['stewardship', 'sự quản lý có trách nhiệm', 'Good stewardship means taking care of shared work.', 'Quản lý có trách nhiệm nghĩa là chăm lo công việc chung.'],
    ['bandwidth', 'khả năng đảm nhận công việc', 'I check my bandwidth before accepting another task.', 'Tôi xem mình còn khả năng đảm nhận công việc không trước khi nhận thêm nhiệm vụ.'],
    ['relay', 'việc chuyển tiếp', 'A clear relay of information helps the next person.', 'Việc chuyển tiếp thông tin rõ ràng giúp người tiếp nhận.'],
    ['deliberation', 'sự cân nhắc kỹ', 'A little deliberation leads to a better decision.', 'Cân nhắc kỹ một chút giúp đưa ra quyết định tốt hơn.'],

    ['verdict', 'kết luận', 'The team reaches a verdict after discussing both options.', 'Cả nhóm đi đến kết luận sau khi bàn cả hai phương án.'],
    ['trajectory', 'xu hướng phát triển', 'Our learning trajectory becomes clearer over time.', 'Xu hướng tiến bộ trong việc học của chúng tôi rõ hơn theo thời gian.'],
    ['precision', 'sự chính xác', 'Precision matters when we check the final details.', 'Sự chính xác quan trọng khi chúng tôi kiểm tra các chi tiết cuối.'],
    ['buffer', 'khoảng thời gian dự phòng', 'A small buffer gives us time to recover from a delay.', 'Một khoảng dự phòng nhỏ cho chúng tôi thời gian khắc phục chậm trễ.'],
    ['dataset', 'bộ dữ liệu', 'I compare the findings with another dataset.', 'Tôi so sánh các phát hiện với một bộ dữ liệu khác.'],
    ['poise', 'sự bình tĩnh tự tin', 'Poise helps me speak clearly in an interview.', 'Sự bình tĩnh tự tin giúp tôi nói rõ trong buổi phỏng vấn.'],
    ['leverage', 'lợi thế có thể tận dụng', 'We use our experience as leverage when choosing priorities.', 'Chúng tôi tận dụng kinh nghiệm làm lợi thế khi chọn việc ưu tiên.'],

    ['nuance', 'sắc thái nhỏ', 'One nuance in the requirement changes our plan.', 'Một sắc thái nhỏ trong yêu cầu làm thay đổi kế hoạch của chúng tôi.'],
    ['breadcrumb', 'dấu vết gợi ý', 'A breadcrumb in the log points to the real problem.', 'Một dấu vết gợi ý trong nhật ký chỉ ra vấn đề thật.'],
    ['go-ahead', 'sự đồng ý cho tiến hành', 'We wait for the go-ahead before releasing the update.', 'Chúng tôi chờ sự đồng ý trước khi phát hành bản cập nhật.'],
    ['wireframe', 'bản khung giao diện', 'A wireframe helps us discuss the page layout.', 'Bản khung giao diện giúp chúng tôi bàn về bố cục trang.'],
    ['segue', 'lời chuyển ý', 'A short segue helps the meeting move to the next topic.', 'Một lời chuyển ý ngắn giúp cuộc họp sang chủ đề tiếp theo.'],
    ['launchpad', 'bước đệm khởi đầu', 'The small page becomes a launchpad for a bigger idea.', 'Trang nhỏ trở thành bước đệm cho một ý tưởng lớn hơn.'],
    ['smoothness', 'sự suôn sẻ', 'The smoothness of the process gives the team confidence.', 'Sự suôn sẻ của quy trình giúp cả nhóm tự tin.'],

    ['spark', 'tia sáng ý tưởng', 'One question can spark a useful new idea.', 'Một câu hỏi có thể khơi lên ý tưởng mới hữu ích.'],
    ['lead', 'đầu mối thông tin', 'A helpful lead takes me to the right resource.', 'Một đầu mối hữu ích dẫn tôi đến đúng tài liệu.'],
    ['pause', 'khoảng dừng', 'A short pause gives us time to revisit the question.', 'Một khoảng dừng ngắn cho chúng tôi thời gian quay lại câu hỏi.'],
    ['opportunity cost', 'chi phí cơ hội', 'We consider the opportunity cost of each option.', 'Chúng tôi cân nhắc chi phí cơ hội của từng phương án.'],
    ['headline', 'dòng tiêu đề', 'A clear headline makes the update easier to notice.', 'Một dòng tiêu đề rõ ràng giúp dễ nhận ra bản cập nhật.'],
    ['snapshot', 'bản ghi nhanh tình hình', 'A daily snapshot shows how the project is moving.', 'Bản ghi nhanh hằng ngày cho thấy dự án đang tiến triển ra sao.'],
    ['synergy', 'sự phối hợp tạo hiệu quả', 'Synergy grows when teammates share their strengths.', 'Sự phối hợp hiệu quả tăng khi đồng đội chia sẻ thế mạnh.'],

    ['candor', 'sự thẳng thắn', 'Candor makes feedback more useful.', 'Sự thẳng thắn khiến góp ý hữu ích hơn.'],
    ['lifeline', 'sự hỗ trợ đúng lúc', 'A quick message from a teammate can be a lifeline.', 'Một tin nhắn nhanh từ đồng đội có thể là sự hỗ trợ đúng lúc.'],
    ['tenacity', 'sự kiên trì bền bỉ', 'Tenacity helps me keep practicing through mistakes.', 'Sự kiên trì bền bỉ giúp tôi tiếp tục luyện dù mắc lỗi.'],
    ['asset', 'tài sản hoặc thiết bị', 'I return the shared asset in good condition.', 'Tôi trả lại thiết bị dùng chung trong tình trạng tốt.'],
    ['readout', 'bản hiển thị kết quả', 'The readout gives us a clue about the system.', 'Bản hiển thị kết quả cho chúng tôi manh mối về hệ thống.'],
    ['dry run', 'buổi chạy thử', 'A dry run helps me prepare for the demo.', 'Một buổi chạy thử giúp tôi chuẩn bị cho phần trình diễn.'],
    ['rationale', 'lý do nền tảng', 'I explain the rationale behind the change.', 'Tôi giải thích lý do nền tảng của thay đổi.'],

    ['pulse', 'nhịp cập nhật', 'A weekly pulse helps me notice new developments.', 'Một nhịp cập nhật hằng tuần giúp tôi nhận ra các diễn biến mới.'],
    ['mastery', 'sự thành thạo', 'Mastery comes from small, regular practice.', 'Sự thành thạo đến từ việc luyện tập đều đặn từng chút.'],
    ['trail', 'chuỗi dấu vết', 'The bug leaves a trail we can follow.', 'Lỗi để lại một chuỗi dấu vết mà chúng tôi có thể lần theo.'],
    ['countdown', 'việc đếm ngược', 'The countdown reminds us that the deadline is near.', 'Việc đếm ngược nhắc chúng tôi rằng hạn chót đã gần.'],
    ['outreach', 'việc chủ động liên hệ', 'A little outreach keeps old teammates connected.', 'Chủ động liên hệ đôi chút giúp các đồng đội cũ giữ kết nối.'],
    ['firewall', 'tường lửa', 'A firewall helps protect the production system.', 'Tường lửa giúp bảo vệ hệ thống thực tế.'],
    ['renewal', 'sự làm mới', 'A short break gives me a sense of renewal.', 'Một giờ nghỉ ngắn cho tôi cảm giác được làm mới.'],

    ['slot', 'khung giờ', 'We find a new slot for the meeting.', 'Chúng tôi tìm một khung giờ mới cho cuộc họp.'],
    ['storyboard', 'bản phác chuỗi trình bày', 'A storyboard keeps the demo easy to follow.', 'Bản phác chuỗi trình bày giúp dễ theo dõi buổi demo.'],
    ['buy-in', 'sự ủng hộ', 'The idea needs team buy-in before we begin.', 'Ý tưởng cần sự ủng hộ của cả nhóm trước khi bắt đầu.'],
    ['pilot', 'đợt áp dụng thử', 'A small pilot shows whether the new process works.', 'Một đợt áp dụng thử nhỏ cho thấy quy trình mới có hiệu quả không.'],
    ['shelf', 'kệ', 'I put the shared device back on the shelf.', 'Tôi đặt thiết bị dùng chung lại lên kệ.'],
    ['emergency', 'tình huống khẩn cấp', 'The team treats the outage as an emergency.', 'Nhóm xem sự gián đoạn là tình huống khẩn cấp.'],
    ['drag', 'sự chậm ì', 'Too much drag makes the page feel slow.', 'Sự chậm ì quá nhiều khiến trang web có cảm giác chậm.'],

    ['glitch', 'trục trặc nhỏ', 'A small glitch appears during testing.', 'Một trục trặc nhỏ xuất hiện trong lúc kiểm thử.'],
    ['headroom', 'phần dung lượng dự phòng', 'More headroom helps the server handle busy hours.', 'Dung lượng dự phòng lớn hơn giúp máy chủ xử lý giờ cao điểm.'],
    ['fixture', 'dữ liệu mẫu kiểm thử', 'A test fixture makes the result repeatable.', 'Dữ liệu mẫu kiểm thử giúp kết quả có thể lặp lại.'],
    ['sounding board', 'người góp ý để thử ý tưởng', 'My teammate acts as a sounding board for the idea.', 'Đồng đội giúp tôi thử và góp ý cho ý tưởng.'],
    ['process ID', 'mã tiến trình', 'A process ID helps us identify the running service.', 'Mã tiến trình giúp chúng tôi xác định dịch vụ đang chạy.'],
    ['ceiling', 'mức trần giới hạn', 'We reach a ceiling and need another approach.', 'Chúng tôi chạm mức trần và cần cách tiếp cận khác.'],
    ['checkpoint', 'điểm kiểm tra', 'The final checkpoint catches a missing step.', 'Điểm kiểm tra cuối phát hiện một bước bị thiếu.'],

    ['token', 'mã xác thực tạm', 'A temporary token expires after a short time.', 'Mã xác thực tạm hết hạn sau một thời gian ngắn.'],
    ['refactor', 'việc cải tổ mã', 'A careful refactor makes shared code easier to maintain.', 'Việc cải tổ mã cẩn thận giúp mã dùng chung dễ bảo trì hơn.'],
    ['lead-up', 'chuỗi sự việc dẫn tới', 'The lead-up to the failure reveals its cause.', 'Chuỗi sự việc dẫn tới lỗi cho thấy nguyên nhân của nó.'],
    ['entry', 'mục ghi', 'I find a useful entry in the documentation.', 'Tôi tìm thấy một mục ghi hữu ích trong tài liệu.'],
    ['mentorship', 'sự cố vấn', 'Mentorship helps me plan my next career step.', 'Sự cố vấn giúp tôi lên kế hoạch cho bước sự nghiệp tiếp theo.'],
    ['watchlist', 'danh sách cần theo dõi', 'I add the unusual case to my watchlist.', 'Tôi thêm trường hợp bất thường vào danh sách cần theo dõi.'],
    ['hindsight', 'cách nhìn lại sau sự việc', 'In hindsight, we could have tested sooner.', 'Nhìn lại sau sự việc, chúng tôi có thể đã kiểm thử sớm hơn.'],

    ['scope creep', 'việc phạm vi tăng dần', 'We notice scope creep before agreeing to more work.', 'Chúng tôi nhận ra phạm vi đang tăng trước khi nhận thêm việc.'],
    ['twist', 'diễn biến bất ngờ', 'A surprising twist changes our original assumption.', 'Một diễn biến bất ngờ thay đổi giả định ban đầu.'],
    ['snowball', 'việc lớn dần rất nhanh', 'A small task can snowball into a large project.', 'Một nhiệm vụ nhỏ có thể nhanh chóng lớn thành dự án lớn.'],
    ['peer', 'người đồng nghiệp ngang hàng', 'A trusted peer can offer helpful advice.', 'Một đồng nghiệp đáng tin có thể cho lời khuyên hữu ích.'],
    ['toggle', 'nút bật tắt', 'I use a toggle to enable debug logging.', 'Tôi dùng nút bật tắt để kích hoạt ghi nhật ký gỡ lỗi.'],
    ['retirement', 'việc ngừng sử dụng', 'We plan the retirement of the old feature flag.', 'Chúng tôi lên kế hoạch ngừng sử dụng cờ tính năng cũ.'],
    ['recovery window', 'khoảng thời gian khắc phục', 'The recovery window gives us time to finish the delayed release.', 'Khoảng thời gian khắc phục cho chúng tôi thời gian hoàn thành đợt phát hành bị chậm.'],

    ['backlog item', 'mục việc tồn', 'We move the urgent backlog item to the top.', 'Chúng tôi đưa mục việc tồn khẩn cấp lên đầu.'],
    ['spike', 'đợt tăng vọt', 'A traffic spike tests the service capacity.', 'Đợt tăng vọt lưu lượng thử thách khả năng đáp ứng của dịch vụ.'],
    ['sanity check', 'bước kiểm tra nhanh', 'A sanity check catches an invalid form value.', 'Bước kiểm tra nhanh phát hiện giá trị biểu mẫu không hợp lệ.'],
    ['retest', 'lần kiểm thử lại', 'A retest confirms that the failure is fixed.', 'Lần kiểm thử lại xác nhận lỗi đã được sửa.'],
    ['tie-breaker', 'tiêu chí phân xử', 'Simplicity becomes the tie-breaker between two approaches.', 'Sự đơn giản trở thành tiêu chí phân xử giữa hai cách làm.'],
    ['polyfill', 'mã bổ sung tính năng thiếu', 'A polyfill can support an older browser.', 'Mã bổ sung có thể hỗ trợ một trình duyệt cũ.'],
    ['green light', 'sự cho phép tiếp tục', 'The successful test gives us the green light.', 'Bài kiểm thử thành công cho chúng tôi sự cho phép tiếp tục.'],

    ['sync', 'buổi đồng bộ thông tin', 'A short sync helps everyone understand the release plan.', 'Một buổi đồng bộ ngắn giúp mọi người hiểu kế hoạch phát hành.'],
    ['sketch', 'bản phác thảo', 'The designer draws a quick sketch of the idea.', 'Nhà thiết kế vẽ một bản phác nhanh cho ý tưởng.'],
    ['matrix', 'bảng đối chiếu', 'A matrix makes the options easier to compare.', 'Bảng đối chiếu giúp dễ so sánh các phương án.'],
    ['walkthrough video', 'video hướng dẫn từng bước', 'A walkthrough video shows each setup step.', 'Video hướng dẫn từng bước cho thấy từng bước thiết lập.'],
    ['red flag', 'dấu hiệu đáng lo', 'I raise a red flag when I see a serious risk.', 'Tôi nêu dấu hiệu đáng lo khi thấy rủi ro nghiêm trọng.'],
    ['caption', 'phụ đề', 'A caption helps more people follow the video.', 'Phụ đề giúp nhiều người theo dõi video hơn.'],
    ['takeaway sentence', 'câu kết luận chính', 'One takeaway sentence makes my point clear.', 'Một câu kết luận chính giúp ý của tôi rõ ràng.'],

    ['drop zone', 'vùng thả tệp', 'I drag the file into the drop zone.', 'Tôi kéo tệp vào vùng thả tệp.'],
    ['handover checklist', 'danh sách bàn giao', 'A handover checklist keeps teams in sync.', 'Danh sách bàn giao giúp các nhóm phối hợp nhịp nhàng.'],
    ['profiling', 'việc đo hiệu năng chi tiết', 'Profiling shows where the page spends time.', 'Việc đo hiệu năng chi tiết cho thấy trang tốn thời gian ở đâu.'],
    ['slack time', 'thời gian dự phòng', 'A little slack time protects the delivery date.', 'Một chút thời gian dự phòng giúp giữ ngày bàn giao.'],
    ['adapter', 'bộ chuyển đổi', 'An adapter helps the app work across platforms.', 'Bộ chuyển đổi giúp ứng dụng hoạt động trên nhiều nền tảng.'],
    ['follow-up note', 'ghi chú theo dõi sau', 'I write a follow-up note after addressing a comment.', 'Tôi viết ghi chú theo dõi sau khi xử lý một nhận xét.'],
    ['fluid grid', 'lưới co giãn', 'A fluid grid adapts to a narrow screen.', 'Lưới co giãn thích ứng với màn hình hẹp.'],

    ['restraint', 'sự tiết chế', 'Restraint helps us keep the design simple.', 'Sự tiết chế giúp chúng tôi giữ thiết kế đơn giản.'],
    ['case study', 'nghiên cứu tình huống', 'A short case study gives me an example I can use.', 'Một nghiên cứu tình huống ngắn cho tôi ví dụ có thể dùng.'],
    ['premise', 'tiền đề', 'We check the premise before accepting the proposal.', 'Chúng tôi kiểm tra tiền đề trước khi chấp nhận đề xuất.'],
    ['blind spot', 'điểm mù trong suy nghĩ', 'A blind spot can hide an important edge case.', 'Một điểm mù có thể che khuất trường hợp biên quan trọng.'],
    ['longevity', 'tuổi thọ sử dụng', 'Longevity matters when we plan maintenance.', 'Tuổi thọ sử dụng quan trọng khi lên kế hoạch bảo trì.'],
    ['self-assessment', 'sự tự đánh giá', 'A self-assessment helps me notice what I learned.', 'Sự tự đánh giá giúp tôi nhận ra mình đã học được gì.'],
    ['caution', 'sự thận trọng', 'Caution helps us avoid a risky change.', 'Sự thận trọng giúp chúng tôi tránh thay đổi nhiều rủi ro.']
];
